apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: talkdesk-callbacks
  name: talkdesk-callbacks
  namespace: talkdesk
spec:
  type: ClusterIP
  selector:
    app: talkdesk-callbacks
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  ipFamilies:
    - IPv4
