// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: missed-call-queued.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MissedCallQueuedRowAppend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventTimestamp            int64  `pb-script-status:"varint,1,opt,name=event_timestamp,json=eventTimestamp,proto3" json:"event_timestamp,omitempty"`
	InteractionId             string `pb-script-status:"bytes,2,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	AttemptNumber             int32  `pb-script-status:"varint,3,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	AvailableAgent            int32  `pb-script-status:"varint,4,opt,name=available_agent,json=availableAgent,proto3" json:"available_agent,omitempty"`
	FailureStatus             bool   `pb-script-status:"varint,5,opt,name=failure_status,json=failureStatus,proto3" json:"failure_status,omitempty"`
	TotalStillNeedingCallback int32  `pb-script-status:"varint,6,opt,name=total_still_needing_callback,json=totalStillNeedingCallback,proto3" json:"total_still_needing_callback,omitempty"`
}

func (x *MissedCallQueuedRowAppend) Reset() {
	*x = MissedCallQueuedRowAppend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_missed_call_queued_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MissedCallQueuedRowAppend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissedCallQueuedRowAppend) ProtoMessage() {}

func (x *MissedCallQueuedRowAppend) ProtoReflect() protoreflect.Message {
	mi := &file_missed_call_queued_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissedCallQueuedRowAppend.ProtoReflect.Descriptor instead.
func (*MissedCallQueuedRowAppend) Descriptor() ([]byte, []int) {
	return file_missed_call_queued_proto_rawDescGZIP(), []int{0}
}

func (x *MissedCallQueuedRowAppend) GetEventTimestamp() int64 {
	if x != nil {
		return x.EventTimestamp
	}
	return 0
}

func (x *MissedCallQueuedRowAppend) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

func (x *MissedCallQueuedRowAppend) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *MissedCallQueuedRowAppend) GetAvailableAgent() int32 {
	if x != nil {
		return x.AvailableAgent
	}
	return 0
}

func (x *MissedCallQueuedRowAppend) GetFailureStatus() bool {
	if x != nil {
		return x.FailureStatus
	}
	return false
}

func (x *MissedCallQueuedRowAppend) GetTotalStillNeedingCallback() int32 {
	if x != nil {
		return x.TotalStillNeedingCallback
	}
	return 0
}

type UserPunchDelivered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventTimestamp int64  `pb-script-status:"varint,1,opt,name=event_timestamp,json=eventTimestamp,proto3" json:"event_timestamp,omitempty"`
	PunchTimestamp int64  `pb-script-status:"varint,2,opt,name=punch_timestamp,json=punchTimestamp,proto3" json:"punch_timestamp,omitempty"`
	UserEmail      string `pb-script-status:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	PunchType      string `pb-script-status:"bytes,4,opt,name=punch_type,json=punchType,proto3" json:"punch_type,omitempty"`
	PunchIdV2      int64  `pb-script-status:"varint,5,opt,name=punch_id_v2,json=punchIdV2,proto3" json:"punch_id_v2,omitempty"`
}

func (x *UserPunchDelivered) Reset() {
	*x = UserPunchDelivered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_missed_call_queued_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPunchDelivered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPunchDelivered) ProtoMessage() {}

func (x *UserPunchDelivered) ProtoReflect() protoreflect.Message {
	mi := &file_missed_call_queued_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPunchDelivered.ProtoReflect.Descriptor instead.
func (*UserPunchDelivered) Descriptor() ([]byte, []int) {
	return file_missed_call_queued_proto_rawDescGZIP(), []int{1}
}

func (x *UserPunchDelivered) GetEventTimestamp() int64 {
	if x != nil {
		return x.EventTimestamp
	}
	return 0
}

func (x *UserPunchDelivered) GetPunchTimestamp() int64 {
	if x != nil {
		return x.PunchTimestamp
	}
	return 0
}

func (x *UserPunchDelivered) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *UserPunchDelivered) GetPunchType() string {
	if x != nil {
		return x.PunchType
	}
	return ""
}

func (x *UserPunchDelivered) GetPunchIdV2() int64 {
	if x != nil {
		return x.PunchIdV2
	}
	return 0
}

var File_missed_call_queued_proto protoreflect.FileDescriptor

var file_missed_call_queued_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x69, 0x73, 0x73, 0x65, 0x64, 0x2d, 0x63, 0x61, 0x6c, 0x6c, 0x2d, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x02, 0x0a, 0x19, 0x6d,
	0x69, 0x73, 0x73, 0x65, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x64, 0x52,
	0x6f, 0x77, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x74, 0x74, 0x65,
	0x6d, 0x70, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x27, 0x0a, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x66, 0x61, 0x69, 0x6c,
	0x75, 0x72, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0d, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x3f, 0x0a, 0x1c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x69, 0x6c, 0x6c, 0x5f, 0x6e,
	0x65, 0x65, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x19, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x74, 0x69, 0x6c,
	0x6c, 0x4e, 0x65, 0x65, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x22, 0xc4, 0x01, 0x0a, 0x12, 0x75, 0x73, 0x65, 0x72, 0x50, 0x75, 0x6e, 0x63, 0x68, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x27, 0x0a, 0x0f, 0x70, 0x75, 0x6e, 0x63, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x70, 0x75, 0x6e, 0x63, 0x68,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x6e, 0x63,
	0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75,
	0x6e, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x70, 0x75, 0x6e, 0x63, 0x68,
	0x5f, 0x69, 0x64, 0x5f, 0x76, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x75,
	0x6e, 0x63, 0x68, 0x49, 0x64, 0x56, 0x32, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_missed_call_queued_proto_rawDescOnce sync.Once
	file_missed_call_queued_proto_rawDescData = file_missed_call_queued_proto_rawDesc
)

func file_missed_call_queued_proto_rawDescGZIP() []byte {
	file_missed_call_queued_proto_rawDescOnce.Do(func() {
		file_missed_call_queued_proto_rawDescData = protoimpl.X.CompressGZIP(file_missed_call_queued_proto_rawDescData)
	})
	return file_missed_call_queued_proto_rawDescData
}

var file_missed_call_queued_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_missed_call_queued_proto_goTypes = []interface{}{
	(*MissedCallQueuedRowAppend)(nil), // 0: missedCallQueuedRowAppend
	(*UserPunchDelivered)(nil),        // 1: userPunchDelivered
}
var file_missed_call_queued_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_missed_call_queued_proto_init() }
func file_missed_call_queued_proto_init() {
	if File_missed_call_queued_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_missed_call_queued_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MissedCallQueuedRowAppend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_missed_call_queued_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPunchDelivered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_missed_call_queued_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_missed_call_queued_proto_goTypes,
		DependencyIndexes: file_missed_call_queued_proto_depIdxs,
		MessageInfos:      file_missed_call_queued_proto_msgTypes,
	}.Build()
	File_missed_call_queued_proto = out.File
	file_missed_call_queued_proto_rawDesc = nil
	file_missed_call_queued_proto_goTypes = nil
	file_missed_call_queued_proto_depIdxs = nil
}
