apiVersion: v1
kind: Service
metadata:
  labels:
    app: talkdesk-cl-testing
  name: talkdesk-cl-testing
  namespace: talkdesk
spec:
  type: ClusterIP
  selector:
    app: talkdesk-cl-testing
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  ipFamilies:
    - IPv4
